version: '3.3'

services:

  reducer:
    environment:
      - GET_HOSTS_FROM=dns
      - USER=test
      - PROJECT=project
      - FLASK_DEBUG=1
      - FLASK_ENV=development
    image: "scaleoutsystems/fedn-reducer:develop"
    build:
      context: ${PWD}
      dockerfile: ${PWD}/components/base/Dockerfile
    working_dir: /app/client
    command: sh -c "pip install -e /app/fedn/ && mkdir -p /app/client/certs && fedn run reducer -n reducer --init=./config/settings-reducer.yaml"
    volumes:
      - ${PWD}/config:/app/client/config
      - ${PWD}/fedn:/app/fedn
    ports:
        - 8090:8090
